### PR TITLE
Open Source Issues

### LINKED ISSUE #3: Add more news sections from the onion website.
Currently the website fetches news from only one section of it "latest news". We can scrap news from different section.
One enhancement to this could be adding filters for each section.

### LINKED ISSUE #4: Responsive UI
Currently, the website isn't responsive. 
We can show cards in different format as the size of device viewing it changes.

### LINKED ISSUE #5: Deployment
This app works locally. Need to deploy it to any platform like heroku or netlify or any such platform.

### LINKED ISSUE #6: Share and report
The user must be able to share the news via external apps such as Whatsapp, Twitter, Telegram, Instagram, Snapchat, Reddit, etc. also a feature to report inappropriate articles must be implemented.

### LINKED ISSUE #7: Migrating from Bootstrap 4 to Bootstrap 5
This project uses Bootstrap 4 , we can migrate to Bootstrap 5.

### LINKED ISSUE #8: Web Scraping : Fix Image not getting rendered.
Image is not getting rendered with old code.

### LINKED ISSUE #9: Toggle : Dark mode and Light Mode

### LINKED ISSUE #11: Readme File Update

### PR DESCRIPTION
**Pull request by SAM-BOGHARA**
* Fixes #7 
* Fixes #9 
* Fixes #8 
* Fixes #6 
* Fixes #4 
* Fixes #11 
* Fixes #3 
* Fixes #4 
* Fixes #5 

1) Bootstrap4 -> Bootsstrap5 Migration
2) Responsive UI
3) Web Scrapped Images, Fixed: Image rendering.
3) Toggle Dark Mode <-> Light Mode
4) Share and report (django-social-share)
5) Copy to clipboard
6) Added New Sections -- news
7) readme File update
8) Deployment : https://news-aggregator-ku26.onrender.com/

### CODE REVIEW

**Comment by sakship31** [comment]
Please update the css of the file to make it look uniform on laptop screen. Its as expected on mobile phone.

**Comment by SAM-BOGHARA** [comment]
Looks fine on laptop 
image

**Comment by SAM-BOGHARA** [comment]
Since we are using django social share package, it is difficult to modify the css for social buttons, hence flexbox is used for all buttons(copy,report,fb,whatsapp,telegram)

**Comment by sakship31** [comment]
For my screen size its a little distorted. I will merge.
image

**Pull request merged**
